<?xml version="1.0"?>
<robot name="jomegatron"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" >

    <!-- all values are in inches and are converted to meters bellow -->
    <property name="pi" value="3.1415"/>
    <property name="in_m" value="0.0254"/>
    
    <property name="base_width" value="28"/>
    <property name="base_length" value="40"/>
    <property name="base_height" value="24"/>
    <property name="base_clearance" value="9.5"/>
    
    <property name="wheel_radius" value="8"/>
    <property name="wheel_width" value="5"/>
    <property name="wheel_setback" value="10"/>
    <property name="wheel_block_height" value="1.5"/>
    <property name="wheel_separation" value="21"/>
    
    <property name="castor_bar_height" value="6"/>
    <property name="castor_bar_width" value="4"/>
    <property name="castor_bar_length" value="5"/>
    <property name="castor_bar_setback" value="25"/>
    
    <property name="castor_radius" value="3"/>
    <property name="castor_width" value="3"/>
    <property name="castor_radius" value="4"/>
    
    
    <property name="mast_base_height" value="16"/>
    <property name="mast_base_width" value="28"/>
    <property name="mast_base_length" value="1"/>
    <property name="mast_base_setback" value="13"/>
    
    <property name="mast_vertical_height" value="5"/>
    <property name="mast_vertical_width" value="1"/>
    <property name="mast_vertical_length" value="1"/>
    
    <property name="mast_horizontal_height" value="1"/>
    <property name="mast_horizontal_width" value="1"/>
    <property name="mast_horizontal_length" value="12"/>
    <property name="mast_horizontal_setback" value="8"/>
    
    <property name="camera_mount_height" value="3.5"/>
    <property name="camera_mount_width" value="3.5"/>
    <property name="camera_mount_length" value="1"/>
    <property name="camera_mount_setback" value="1"/>
    
    <property name="pt_grey_height" value="2"/>
    <property name="pt_grey_width" value="3"/>
    <property name="pt_grey_length" value="1.5"/>

    


    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="Grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    
    <material name="Shadow">
        <color rgba="0.25 0.25 0.25 1"/>
    </material>

    <!-- robot footprint -->
    <link name="base_footprint">
        <inertial>
          <mass value="0.0001" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} 0.001" />
            </geometry>
            <material name="Shadow" />
        </visual>

        <collision>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} 0.001" />
            </geometry>
        </collision>
    </link>
    
    
    <!-- robot base -->
    <link name="base_link">
        <inertial>
            <mass value="50" />
            <origin xyz="0 0 0.0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
            iyy="0.01" iyz="0.0" izz="0.5" />
        </inertial>

        <visual>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 ${base_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} ${base_height*in_m}" />
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <origin xyz="${-(base_length/2-wheel_setback)*in_m} 0 ${base_height/2*in_m}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length*in_m} ${base_width*in_m} ${base_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${base_clearance*in_m}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>
    
    
    <!-- left wheel -->
    <link name="left_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 ${-wheel_separation/2*in_m} ${-wheel_block_height*in_m} " rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    
    <!-- right wheel -->
    <link name="right_wheel_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="2" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 ${wheel_separation/2*in_m} ${-wheel_block_height*in_m} " rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0 1 0"/>
    </joint>
    


</robot>
