<?xml version="1.0"?>
<robot name="jomegatron"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" >

    <!-- all values are in inches -->
    <property name="pi" value="3.1415"/>
    <property name="in_m" value="0.0254"/>
    <property name="cos_2_3_pi" value="-0.5"/>
    <property name="sin_2_3_pi" value="0.866025"/>
    <property name="cos_4_3_pi" value="-0.5"/>
    <property name="sin_4_3_pi" value="-0.866025"/>
   
   
   
    <property name="base_radius" value="12"/>
    <property name="base_height" value=".5"/>
   
    
    <!-- motors are in inches -->
    <property name="motor_height" value="2"/>
    <property name="motor_width" value="2"/>
    <property name="motor_length" value="4"/>
    <property name="motor_placement_radius" value="6"/>
    
    
    <!-- wheels are in inches-->
    <property name="wheel_radius" value="2"/>
    <property name="wheel_width" value="1"/>
    <property name="wheel_axil_offset" value="1.5"/>

    
    <property name="castor_bar_height" value="6"/>
    <property name="castor_bar_width" value="4"/>
    <property name="castor_bar_length" value="5"/>
    <property name="castor_bar_setback" value="25"/>
    
    <property name="castor_radius" value="3"/>
    <property name="castor_width" value="3"/>
    <property name="castor_radius" value="4"/>
    
    
    <property name="mast_base_height" value="16"/>
    <property name="mast_base_width" value="28"/>
    <property name="mast_base_length" value="1"/>
    <property name="mast_base_setback" value="13"/>
    
    <property name="mast_vertical_height" value="5"/>
    <property name="mast_vertical_width" value="1"/>
    <property name="mast_vertical_length" value="1"/>
    
    <property name="mast_horizontal_height" value="1"/>
    <property name="mast_horizontal_width" value="1"/>
    <property name="mast_horizontal_length" value="12"/>
    <property name="mast_horizontal_setback" value="8"/>
    
    <property name="camera_mount_height" value="3.5"/>
    <property name="camera_mount_width" value="3.5"/>
    <property name="camera_mount_length" value="1"/>
    <property name="camera_mount_setback" value="1"/>
    
    <property name="pt_grey_height" value="2"/>
    <property name="pt_grey_width" value="3"/>
    <property name="pt_grey_length" value="1.5"/>

    


    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>
    
    <material name="Black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="Grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    
    <material name="Shadow">
        <color rgba="0.25 0.25 0.25 1"/>
    </material>

    <!-- robot footprint -->
    <link name="base_footprint">
        <inertial>
          <mass value="0.0001" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius*in_m}" length = ".001"/>
            </geometry>
            <material name="Shadow" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius*in_m}" length = ".01"/>
            </geometry>
        </collision>
    </link>
    
    
    <!-- robot base -->
    <link name="base_link">
        <inertial>
          <mass value="5" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="0 0 ${(base_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius*in_m}" length = "${base_height*in_m}"/>
            </geometry>
            <material name="Grey" />
        </visual>

        <collision>
            <origin xyz="0 0 ${(base_height/2)*in_m}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${base_radius*in_m}" length = "${base_height*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${(motor_height/2 + wheel_radius)*in_m}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>
    
    <!-- motor 0 -->
    <link name="motor_0_link">
        <inertial>
          <mass value="2" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="motor_0_joint" type="fixed">
        <origin xyz="${motor_placement_radius * in_m} 0 ${-motor_height/2 *in_m}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="motor_0_link" />
    </joint>
    
    <!-- wheel 0 -->
    <link name="wheel_0_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="wheel_0_joint" type="continuous">
        <origin xyz="${wheel_axil_offset * in_m} 0 0" rpy="0 0 0"/>
        <parent link="motor_0_link"/>
        <child link="wheel_0_link"/>
        <axis xyz="1 0 0"/>
    </joint>
    
    
    
    <!-- motor 1 -->
    <link name="motor_1_link">
        <inertial>
          <mass value="2" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="motor_1_joint" type="fixed">
        <origin xyz="${motor_placement_radius * cos_2_3_pi * in_m} ${motor_placement_radius * sin_2_3_pi *in_m} ${-motor_height/2 *in_m}" rpy="0 0 ${(2*pi)/3}" />
        <parent link="base_link"/>
        <child link="motor_1_link" />
    </joint>
    
    <!-- wheel 1 -->
    <link name="wheel_1_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="wheel_1_joint" type="continuous">
        <origin xyz="${wheel_axil_offset * in_m} 0 0" rpy="0 0 0"/>
        <parent link="motor_1_link"/>
        <child link="wheel_1_link"/>
        <axis xyz="1 0 0"/>
    </joint>
    
    <!-- motor 2 -->
    <link name="motor_2_link">
        <inertial>
          <mass value="2" />
          <origin xyz="0 0 0" />
          <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                  iyy="0.0001" iyz="0.0" 
                  izz="0.0001" />
        </inertial>
        
        <visual>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
            <material name="Black" />
        </visual>

        <collision>
            <origin xyz="${-motor_length/2 * in_m} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${motor_length *in_m} ${motor_width*in_m} ${motor_height*in_m}" />
            </geometry>
        </collision>
    </link>
    
    <joint name="motor_2_joint" type="fixed">
        <origin xyz="${motor_placement_radius * cos_4_3_pi * in_m} ${motor_placement_radius * sin_4_3_pi *in_m} ${-motor_height/2 *in_m}" rpy="0 0 ${(4*pi)/3}" />
        <parent link="base_link"/>
        <child link="motor_2_link" />
    </joint>
    
    <!-- wheel 2 -->
    <link name="wheel_2_link">
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value=".5" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
            iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder radius="${wheel_radius*in_m}" length = "${wheel_width*in_m}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="wheel_2_joint" type="continuous">
        <origin xyz="${wheel_axil_offset * in_m} 0 0" rpy="0 0 0"/>
        <parent link="motor_2_link"/>
        <child link="wheel_2_link"/>
        <axis xyz="1 0 0"/>
    </joint>
    
    


</robot>
